export const elements = {
    inputEmailUsuario: 'input[id="email"]',
    inputSenhaUsuario: 'input[id="password"]',
    btnEntrarSistema: '[data-testid="entrar"]',
    checkBoxAdministrador: '[class="form-check-label"]',
    mensagemValidarLoginSucesso:'[class="message form-text"]',
    linkCadastrarNovoUsuario:'[data-testid="cadastrar"]',
    btnCadastrar:'[data-testid="cadastrar"]',
    validacaoCadastro:'[class="message form-text"]',
    inputNomeUsuario:'input[id="nome"]',
    validarUsuarioLogado:'[data-testid="logout"]',
    validarCampoEmbranco: '[class="alert alert-secondary alert-dismissible"]',
    mensagemCadastroComSucesso:'[class="alert-link"]',
    sairDoSistema:'[data-testid="logout"]',
}